version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    platform: linux/amd64 
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=simple_auth_app

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    platform: linux/amd64 
    ports:
      - "3000:3000"
    depends_on:
      - server

  db:
    image: mysql:5.7
    platform: linux/amd64 
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: simple_auth_app
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
